name: CI
on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  
jobs:
  build:
    name: build
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS Credentials rick
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::612281548001:role/GithubActionsRoleFromTF
          role-session-name: GithubActionsSession
      
      - run: aws sts get-caller-identity

